path_to_images: "/Users/Sunsmeister/Desktop/Research/Brain/MultiView/3D-Animal-Pose/data/IBL_example/e5fae088-ed96-4d9b-82f9-dfd13c259d52_trials_10_13/images" # Should be a folder containing subfolders with frames from each view
path_to_points: "/Users/Sunsmeister/Desktop/Research/Brain/MultiView/3D-Animal-Pose/data/ibl.npy" # Shape must be (num_cameras, num_frames, num_bodyparts, 2)
intrinsics:
    focal_length:
        focal_length_mm: 16
        sensor_size: 12.7
extrinsics: # NOTE: defaults to [0,0,0]
    translation: 
        cam1: [0, 0, 0]
        cam2: [-1.5664, 0, 2.4738]
    rotation: # Each entry will be multiplied by pi
        cam1: [0, 0, 0]
        cam2: [0, 2.0127/pi, 0]
bp_names: 
    - 'paw1'
    - 'paw2'
    - 'nose'
skeleton:
    - ['paw1', 'nose']
    - ['paw2', 'nose']
color_list:
    - 'green'
    - 'green'
    - 'purple'