path_to_videos:
- /Volumes/sawtell-locker/C1/free/vids/20201102_Joao/concatenated.avi

path_to_csv:
- /Volumes/sawtell-locker/C1/free/vids/20201102_Joao/concatenated_tracking.csv

intrinsics:
  focal_length:
    focal_length_mm: 15
    sensor_size: 12

extrinsics: # NOTE: len(x) = len(y) = len(z) = number of cameras
  translation:
    cam1: [0, -1.94, 1.72]
    cam2: [0, 0, 0]
    cam3: [1.86, 0, 1.72]
  rotation:   # Each entry will be multiplied by pi
    cam1: [-1/2, 0, 0]
    cam2: [0, 0, 0]
    cam3: [0, -1/2, 0]

mirrored: true

image_limits: # If all views are in image (mirror, for example), need to specify boundaries
  height_lims: [[0, 165], [165, -1], [165, -1]]
  width_lims: [[0, -1], [0, -1], [318, -1]]

point_sizes: 4

bp_names:
- head
- chin_base
- chin1_4
- chin_half
- chin3_4
- chin_tip
- mid
- tail_neck
- caudal_d
- caudal_v
- worm_1
- worm_2
- worm_3
- worm_4
- worm_5
- pectoral_L
- pectoral_R
- pectoral_L_base
- pectoral_R_base



skeleton:
  - [chin_base, head]
  - [chin1_4, chin_base]
  - [chin_half, chin1_4]
  - [chin3_4, chin_half]
  - [chin_tip, chin3_4]
  - [mid, head]
  - [worm_1, worm_2]
  - [worm_2, worm_3]
  - [worm_3, worm_4]
  - [worm_4, worm_5]

color_list:
- blue
- red
- red
- red
- red
- red
- white
- orange
- green
- green
- yellow
- yellow
- yellow
- yellow
- yellow
- purple
- purple
- green 
- green



view_names:
  - top
  - main
  - right
