path_to_videos:
- /Volumes/sawtell-locker/C1/free/vids/20201104_Joao/concatenated.avi

path_to_csv:
- /Volumes/sawtell-locker/C1/free/vids/20201104_Joao/concatenated_tracking.csv

intrinsics:
  focal_length: 0.231
    focal_length_mm:
    sensor_size:

extrinsics: # NOTE: len(x) = len(y) = len(z) = number of cameras
  translation:
    cam1: [-.54, +1.94, -1.11]
    cam2: [0, 0, 0]
    cam3: [0.4, 0, -1.4]
  rotation:   # Each entry will be multiplied by pi
    cam1: [-.5, .34, 0.2]
    cam2: [2., -0.33, 0.1]
    cam3: [.4, -2.1, -2.1]

mirrored: true

image_limits: # If all views are in image (mirror, for example), need to specify boundaries
  height_lims: [[0, 165], [165, -1], [165, -1]]
  width_lims: [[0, -1], [0, -1], [318, -1]]

point_sizes: 3

bp_names:
- head
- chin_base
- chin1_4
- chin_half
- chin3_4
- chin_tip
- mid
- tail_neck
- caudal_d
- caudal_v
- pectoral_L
- pectoral_R
- pectoral_L_base
- pectoral_R_base
#- worm_1
#- worm_2
#- worm_3
#- worm_4
#- worm_5

skeleton:
  - [chin_base, head]
  - [chin1_4, chin_base]
  - [chin_half, chin1_4]
  - [chin3_4, chin_half]
  - [chin_tip, chin3_4]
  - [mid, head]
  - [tail_neck, mid]
  - [tail_neck, caudal_d]
  - [tail_neck, caudal_v]
  - [pectoral_L, pectoral_L_base]
  - [pectoral_L_base, head]
  - [pectoral_R, pectoral_R_base]
  - [pectoral_R_base, head]
  #- [worm_1, worm_2]
  #- [worm_2, worm_3]
  #- [worm_3, worm_4]
  #- [worm_4, worm_5]

color_list:
- blue
- red
- red
- red
- red
- red
- white
- orange
- green
- green
- purple
- purple
- purple
- purple
#- yellow
#- yellow
#- yellow
#- yellow
#- yellow

view_names:
  - top
  - main
  - right

